<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * *********************************************************************************** */
$languageStrings = array(
	'Activity Type' => 'Тип на действието',
	'Call' => 'Обаждане',
	'Completed' => 'Завършено',
	'Daily' => 'Ден(и)',
	'Deferred' => 'Отложено',
	'End Date & Time' => 'Крайна дата и час',
	'first' => 'Първи',
	'ICAL_FORMAT' => 'iCal формат',
	'last' => 'Последен',
	'LBL_ACTIVITY_TYPES' => 'Видове действия',
	'LBL_ADD_CALENDAR_VIEW' => 'Добавяне на събитие',
	'LBL_ADDED_CALENDARS' => 'Добавени събития',
	'LBL_ADD_EVENT' => 'Добавяне на събитие',
	'LBL_ADD_TASK' => 'Добави Ангажимент',
	'LBL_CALENDAR_SETTINGS' => 'Настройки на календара',
	'LBL_CALENDAR_SHARING' => 'Споделяне на календара',
	'LBL_CALENDAR_VIEW' => 'Моят календар',
	'LBL_CALL' => 'Обаждане',
	'LBL_CHANGE_OWNER' => 'Смяна на отговорник',
	'LBL_CONTACTS_BIRTH_DAY' => 'Рожденна дата',
	'LBL_CONTACTS_SUPPORT_END_DATE' => 'Крайна дата на подръжка',
	'LBL_DAY0' => 'Неделя',
	'LBL_DAY1' => 'Понеделник',
	'LBL_DAY2' => 'Вторник',
	'LBL_DAY3' => 'Сряда',
	'LBL_DAY4' => 'Четвъртък',
	'LBL_DAY5' => 'Петък',
	'LBL_DAY6' => 'Събота',
	'LBL_DAY_OF_THE_MONTH' => 'Ден от месеца',
	'LBL_DEFAULT_EVENT_DURATION' => 'Продължителност на събитието',
	'LBL_DEFAULT_STATUS_TYPE' => 'Default Status & Type',
	'LBL_DELETE_CALENDAR' => 'Изтриване на събитие',
	'LBL_EDIT_COLOR' => 'Цвят',
	'LBL_EDITING_CALENDAR_VIEW' => 'Редактиране на изгледа',
	'LBL_EVENT' => 'Събитие',
	'LBL_EVENT_INFORMATION' => 'Детайли',
	'LBL_EVENT_OR_TASK' => 'Събитие / Ангажимент',
	'LBL_EVENTS' => 'Събития',
	'LBL_FINISH' => 'Край',
	'LBL_IMPORT_RECORDS' => 'Зареждане на записи',
	'LBL_LAST_IMPORT_UNDONE' => 'Неуспешно импортиране',
	'LBL_MINUTES' => 'Минути',
	'LBL_ON' => 'на',
	'LBL_OTHER_EVENTS' => 'Други събития',
	'LBL_RECORDS_LIST' => 'Списък', //Duplicated key-value pair
	'LBL_RESULT' => 'Резултат',
	'LBL_SELECT_ACTIVITY_TYPE' => 'Избор на действие',
	'LBL_SELECT_CALENDAR_COLOR' => 'Избор на цвят на събитието',
	'LBL_SELECT_USER_CALENDAR' => 'Избор на потребителски календар',
	'LBL_SELECT_USERS' => 'Избор на потребители',
	'LBL_SHARED_CALENDAR' => 'Споделен календар',
	'LBL_STATUS' => 'Status',
	'LBL_TASK_INFORMATION' => 'Детайли',
	'LBL_TASKS' => 'Ангажимент',
	'LBL_TASK' => 'Ангажимент',
	'LBL_TODOS' => 'Ангажимент',
	'LBL_TOTAL_EVENTS_IMPORTED' => 'No. of Events Successfully Imported ',
	'LBL_TOTAL_EVENTS_SKIPPED' => 'No. of Events Skipped as they were missing one or more required field ',
	'LBL_TOTAL_TASKS_IMPORTED' => 'No. of Tasks Successfully Imported ',
	'LBL_TOTAL_TASKS_SKIPPED' => 'No. of Tasks Skipped as they were missing one or more required field ',
	'LBL_TYPE' => 'Тип',
	'LBL_UNDO_LAST_IMPORT' => 'Undo Last Import',
	'Location' => 'Местонахождение',
	'Medium' => 'Средно',
	'Meeting' => 'Среща',
	'Monthly' => 'Ежемесечно',
	'Not Started' => 'Незапочнало',
	'Pending Input' => 'Изчакване',
	'Planned' => 'Планирано',
	'Send Notification' => 'Изпращане на уведомление',
	'SINGLE_Calendar' => 'Ангажимент',
	'SINGLE_Events' => 'Събитие',
	'Start Date & Time' => 'Начална дата и час',
	'Subject' => 'Тема',
	'Tasks' => 'Ангажимент',
	'Task' => 'Ангажимент',
	'Weekly' => 'Седмица(и)',
	'Yearly' => 'Година',
    
         //Patch provided by http://trac.vtiger.com/cgi-bin/trac.cgi/ticket/7884
        'Start Date &amp; Time' => 'Начална дата и час', 
        'End Date &amp; Time' => 'Крайна дата и час', 
        'End Date' => 'Крайна дата', 
    
        //Event Status picklist values 
        'Held' => 'Задържано', 
        'Not Held' => 'Незадържано', 
);

$jsLanguageStrings = array(
	'JS_CALENDAR_VIEW_ADDED_SUCCESSFULLY' => 'Успешно добавен изглед',
	'JS_CALENDAR_VIEW_COLOR_UPDATED_SUCCESSFULLY' => 'Успешно обновяване на цвета', 
	'JS_CALENDAR_VIEW_DELETE_CONFIRMATION' => 'Сигурни ли сте, че искате да изтриете този изглед ?', 
	'JS_CALENDAR_VIEW_DELETED_SUCCESSFULLY' => 'Изгледа е изтрит успешно',
	'JS_EDIT_CALENDAR' => 'Редактиране на събитие',
        'JS_FUTURE_EVENT_CANNOT_BE_HELD' => 'Не може да се задържи бъдещо събитие', 
	'JS_NO_CALENDAR_VIEWS_TO_ADD' => 'Няма изгледи за добавяне',
        'JS_NO_DELETE_PERMISSION' => 'Нямате нужните права за изтриване на събития в календара.', 
        'JS_NO_EDIT_PERMISSION' => 'Нямата нужните права за модефициране на календара', 
        'JS_TASK_IS_SUCCESSFULLY_ADDED_TO_YOUR_CALENDAR' => 'Ангажиментът беше успешно добавен в календара', 
        'JS_RECORD_DELETED' => 'Събитието беше изтрито успешно', 
	'LBL_ADD_EVENT_TASK' => 'Добави Събитие / Ангажимент',
	'LBL_ALL_DAY' => 'Цял ден',
	'LBL_APR' => 'Апр',
	'LBL_APRIL' => 'Април',
	'LBL_AUG' => 'Авг',
	'LBL_AUGUST' => 'Август',
	'LBL_CANT_SELECT_CONTACT_FROM_LEADS' => 'Не може да изберете контакт от потенциален клиент',
	'LBL_DAY' => 'Ден',
	'LBL_DEC' => 'Дек',
	'LBL_DECEMBER' => 'Декември',
	'LBL_FEB' => 'Фев',
	'LBL_FEBRUARY' => 'Февруари',
	'LBL_FRIDAY' => 'Петък',
	'LBL_FRI' => 'Пет',
	'LBL_JAN' => 'Яну',
	'LBL_JANUARY' => 'Януари',
	'LBL_JUL' => 'Юли',
	'LBL_JULY' => 'Юли',
	'LBL_JUNE' => 'Юни',
	'LBL_JUN' => 'Юни',
	'LBL_MARCH' => 'Мар',
	'LBL_MAR' => 'Март',
	'LBL_MAY' => 'Май',
	'LBL_MAY' => 'Май',
	'LBL_MONDAY' => 'Понеделник',
	'LBL_MON' => 'Пон',
	'LBL_MONTH' => 'Месец',
	'LBL_NOVEMBER' => 'Ноември',
	'LBL_NOV' => 'Ное',
	'LBL_OCTOBER' => 'Октомври',
	'LBL_OCT' => 'Окт',
	'LBL_SAT' => 'Съб',
	'LBL_SATURDAY' => 'Събота',
	'LBL_SEP' => 'Сеп',
	'LBL_SEPTEMBER' => 'Септември',
	'LBL_SUNDAY' => 'Неделя',
	'LBL_SUN' => 'Нед',
	'LBL_THURSDAY' => 'Четвъртък',
	'LBL_THU' => 'Чет',
	'LBL_TODAY' => 'Днес',
	'LBL_TUESDAY' => 'Вторник',
	'LBL_TUE' => 'Втр',
	'LBL_WEDNESDAY' => 'Сряда',
	'LBL_WED' => 'Сря',
	'LBL_WEEK' => 'Седмица',
	'Mobile Call' => 'Повикване по мобилен телефон',
);
