<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'Admin' => 'Admin',
	'Asterisk Configuration'  =>  'Asterisk Configuration',
	'Asterisk Extension'  =>  'Asterisk Extension',
	'Calendar Hour Format' => 'Calendar Hour Format',
	'Confirm Password' => 'Потвърди парола',
	'Date Format' => 'Формат на датата',
	'Decimal Separator'  =>  'Десетичен разделител',
	'Default Activity View' => 'Изглед на календара',
	'Default Call Duration' => 'Default Call Duration (Mins)',
	'Default Lead View' => 'Default Lead View',
	'Department' => 'Отдел',
	'Detail' => 'Detail',
	'Digit Grouping Pattern'  =>  'Digit Grouping Pattern',
	'Digit Grouping Separator'  =>  'Digit Grouping Separator',
	'ForgotPassword' => 'Забравена парола',
	'Home Phone' => 'Домашен телефон',
	'INTERNAL_MAIL_COMPOSER' => 'Вграден мениджър на пощата',
	'Language' => 'Език',
	'LBL_ABOUT_ME'		=>	'За мен',
	'LBL_ACTIVE_USERS' => 'Актиовни потребители',
	'LBL_ADD_RECORD' => 'Добави потребител',
	'LBL_ADDRESS_INFORMATION' => 'Адрес на потребителя',
	'LBL_ALL_FIELDS_BELOW_ARE_REQUIRED'		=>	'(Всички полета по-долу са задължителни)',
	'LBL_ALMOST_THERE'	=>	'Край!',
	'LBL_BASE_CURRENCY'		=> 'Базова валута',
	'LBL_CHANGE_PASSWORD' => 'Промяна на парола',
	'LBL_CHOOSE_BASE_CURRENCY'	=> 'Избор на базова валута',
	'LBL_CHOOSE_DATE_FORMAT'=> 'Избор на формат на дата',
	'LBL_CHOOSE_LANGUAGE'	=> 'Избор на език',
	'LBL_CHOOSE_TIMEZONE'	=> 'Избор на часова зона',
	'LBL_COMPANY_SIZE'		=> 'Големина на компанията',
	'LBL_CONFIRM_PASSWORD' => 'Потвърди парола',
	'LBL_CONNECT_WITH_US' => 'Връзка с нас',
	'LBL_CURRENCY_CONFIGURATION' =>  'Конфигурация на валута',
	'LBL_DATE_FORMAT'		=> 'Формат на датата',
	'LBL_DELETE_GROUP' => 'Изтриване на група',
	'LBL_DELETE_GROUPNAME' => 'Група за изтриване',
	'LBL_DELETE_PROFILE' => 'Изтриване на профил',
	'LBL_DELETE_USER_PERMANENTLY' => 'Изтрий потребителя перманентно',
	'LBL_DELETE_USER' => 'Потребител, който да бъде изтрит',
	'LBL_DEPARTMENT'		=> 'Отдел',
	'LBL_EMAIL_SEND' => 'Изпратено е съобщение на електронната поща за промяна на паролата.',
	'LBL_GET_MORE' => 'Научи повече за системата',
	'LBL_GET_STARTED'	=> 'Да започваме',
	'LBL_HIDDEN' => 'Скрити',
	'LBL_HIDE' => 'Скрий',
	'LBL_HOME_PAGE_COMPO' => 'Компоненти за домашна страница',
	'LBL_HOME_PAGE_COMPONENTS' => 'Компоненти за домашна страница',
	'LBL_INACTIVE_USERS' => 'Неактивни потребители',
	'LBL_INVALID_USER_OR_EMAIL' => 'Невалиднио потребителско име или имейл.',
	'LBL_INVALID_USER_OR_PASSWORD' => 'Невалидно потребителско име и/или парола.',
	'LBL_JOB_TITLE'			=> 'Длъжност',
	'LBL_LANGUAGE' => 'Език',
	'LBL_LOGIN_AS' => 'Вход с ',
	'LBL_LOGIN_HISTORY' => 'История на влизанията',
	'LBL_MORE_INFORMATION'  =>  'Повече информация',
	'LBL_MY_PREFERENCES'  =>  'Моите предпочитания',
	'LBL_NEW_PASSWORD' => 'Нова парола',
	'LBL_OLD_PASSWORD' => 'Стара парола',
	'LBL_OPERATING_CURRENCY'	=> 'Базовата валута не може да бъде модифицирана.Изберете валута с която ще се оперира',
	'LBL_PHONE'	=> 'Телефон',
	'LBL_PROFILE_TO_BE_DELETED' => 'Профил за изтриване',
	'LBL_RESTORE' => 'Възстанови',
	'LBL_SELECT_COUNTRY'	=> 'Избор на държава',
	'LBL_SHOWN' => 'Показано',
	'LBL_SHOW' => 'Покажи',
	'LBL_TAG_CLOUD_DISPLAY' => 'Показване на ТАГ каре',
	'LBL_TO_CRM' => 'Вход в системата',
	'LBL_TRANSFER_GROUP' => 'Транфериране на собственноста до: ',
	'LBL_TRANSFER_OWNERSHIP' => 'Транфериране на собственост',
	'LBL_TRANSFER_RECORDS_TO_USER' => 'Транфериране на записите до',
	'LBL_TRANSFER_ROLES_TO_PROFILE' => 'транфериране на ролите до профил',
	'LBL_TRANSFER_USER' => 'Транфериране на собственноста на',
	'LBL_USER_ADV_OPTIONS' => 'Разширени потребителски настройки',
	'LBL_USER_DELETED_SUCCESSFULLY' => 'Потребителя е изтрит успешно',
	'LBL_USERDETAIL_INFO' => 'Преглед на детайлите за потребителя',
	'LBL_USER_IMAGE_INFORMATION' => 'Снимка',
	'LBL_USER_LIST_DETAILS' => 'Детайли',
	'LBL_USERLOGIN_ROLE'  =>  'Потребител & Роля',
	'LBL_USER_RESTORED_SUCCESSFULLY' => 'Потребителя е възстановен успешно',
	'LBL_USER_TO_BE_DELETED' => 'Потребител, който да бъде изтрит',
	'LBL_WE_PROMISE_TO_KEEP_THIS_PRIVATE'	=>	'(Обещаваме това да не бъде споделяно)',
	'LBL_WHERE_ARE_YOU_FROM' =>	'От къде сте?',
	'LBL_YOUR_CONTACT_NUMBER' => 'Вашият номер за връзка',
	'Number Of Currency Decimals'  =>  'Закръгляне до',
	'Office Phone' => 'Служебен телефон',
	'Other Event Duration' => 'Other Event Duration (Mins)',
	'Password' => 'Парола',
	'Receive Incoming Calls'  =>  'Приеми обаждане',
	'Reports To' => 'Докладвай до',
	'Role' => 'Роля',
	'Signature' => 'Подпис',
	'Street Address' => 'Адрес',
	'Summary' => 'Резюме',
	'Symbol Placement'  =>  'Позици	на символа',
	'Tag Cloud' => 'ТАГ Облак',
	'Theme' =>  'Тема',
	'Time Zone'  =>  'Часова зона',
	'Title' => 'Заглавие',
	'Truncate Trailing Zeros'  =>   'Премахване на продължаващите нули',
	'User Image' => 'Снимка',
	'User Name' => 'Потребителско име',
	'Webservice Access Key' => 'Ключ за достъп',
	'Yahoo id' => 'Yahoo id',
    
         //Patch provided by http://trac.vtiger.com/cgi-bin/trac.cgi/ticket/7884
        'Day starts at' => 'Деня започва от', 

        //User status 
        'Active' => 'Активен', 
        'Inactive' => 'Неактивен', 

        //Lead View settings 
        'Today' => 'Днес', 
        'Last 2 Days' => 'Последните 2 дни', 
        'Last Week' => 'Миналата седмица', 

        //Calendar settings 
        'This Week' => 'Тази седмица', 
        'This Month' => 'Този месец', 
        'This Year' => 'Тази година', 

        'Sunday' => 'Неделя', 
        'Monday' => 'Понеделник', 
        'Tuesday' => 'Вторник', 
        'Wednesday' => 'Сряда', 
        'Thursday' => 'Четвъртък', 
        'Friday' => 'Петък', 
        'Saturday' => 'Събота', 

        '1 Minute' => '1 минута', 
        '5 Minutes' => '5 минути', 
        '15 Minutes' => '15 минути', 
        '30 Minutes' => '30 минути', 
        '45 Minutes' => '45 минути', 
        '1 Hour' => '1 час', 
        '1 Day' => '1 ден', 

	//Time zones-Dont change any value
    'Kwajalein'  =>  '(UTC-12:00) International Date Line West',
    'Pacific/Midway'  =>  '(UTC-11:00) Coordinated Universal Time-11',
    'Pacific/Samoa'  =>  '(UTC-11:00) Samoa',
    'Pacific/Honolulu'  =>  '(UTC-10:00) Hawaii',
    'America/Anchorage'  =>  '(UTC-09:00) Alaska',
    'America/Los_Angeles'  =>  '(UTC-08:00) Pacific Time (US &amp; Canada)',
    'America/Tijuana'  =>  '(UTC-08:00) Tijuana, Baja California',
    'America/Denver'  =>  '(UTC-07:00) Mountain Time (US &amp; Canada)',
    'America/Chihuahua'  =>  '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
    'America/Mazatlan'  =>  '(UTC-07:00) Mazatlan',
    'America/Phoenix'  =>  '(UTC-07:00) Arizona',
    'America/Regina'  =>  '(UTC-06:00) Saskatchewan',
    'America/Tegucigalpa'  =>  '(UTC-06:00) Central America',
    'America/Chicago'  =>  '(UTC-06:00) Central Time (US &amp; Canada)',
    'America/Mexico_City'  =>  '(UTC-06:00) Mexico City',
    'America/Monterrey'  =>  '(UTC-06:00) Monterrey',
    'America/New_York'  =>  '(UTC-05:00) Eastern Time (US &amp; Canada)',
    'America/Bogota'  =>  '(UTC-05:00) Bogota, Lima, Quito',
    'America/Lima'  =>  '(UTC-05:00) Lima',
    'America/Rio_Branco'  =>  '(UTC-05:00) Rio Branco',
    'America/Indiana/Indianapolis'  =>  '(UTC-05:00) Indiana (East)',
    'America/Caracas'  =>  '(UTC-04:30) Caracas',
    'America/Halifax'  =>  '(UTC-04:00) Atlantic Time (Canada)',
    'America/Manaus'  =>  '(UTC-04:00) Manaus',
    'America/Santiago'  =>  '(UTC-04:00) Santiago',
    'America/La_Paz'  =>  '(UTC-04:00) La Paz',
    'America/Cuiaba'  =>  '(UTC-04:00) Cuiaba',
    'America/Asuncion'  =>  '(UTC-04:00) Asuncion',
    'America/St_Johns'  =>  '(UTC-03:30) Newfoundland',
    'America/Argentina/Buenos_Aires'  =>  '(UTC-03:00) Buenos Aires',
    'America/Sao_Paulo'  =>  '(UTC-03:00) Brasilia',
    'America/Godthab'  =>  '(UTC-03:00) Greenland',
    'America/Montevideo'  =>  '(UTC-03:00) Montevideo',
    'Atlantic/South_Georgia'  =>  '(UTC-02:00) Mid-Atlantic',
    'Atlantic/Azores'  =>  '(UTC-01:00) Azores',
    'Atlantic/Cape_Verde'  =>  '(UTC-01:00) Cape Verde Is.',
    'Europe/London'  =>  '(UTC) London, Edinburgh, Dublin, Lisbon',
    'UTC'  =>  '(UTC) Coordinated Universal Time, Greenwich Mean Time',
    'Africa/Monrovia'  =>  '(UTC) Monrovia, Reykjavik',
    'Africa/Casablanca'  =>  '(UTC) Casablanca',
    'Europe/Belgrade'  =>  '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
    'Europe/Sarajevo'  =>  '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
    'Europe/Brussels'  =>  '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
    'Africa/Algiers'  =>  '(UTC+01:00) West Central Africa',
    'Europe/Amsterdam'  =>  '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
    'Europe/Minsk'  =>  '(UTC+02:00) Minsk',
    'Africa/Cairo'  =>  '(UTC+02:00) Cairo',
    'Europe/Helsinki'  =>  '(UTC+02:00) Helsinki, Riga, Sofia, Tallinn, Vilnius',
    'Europe/Athens'  =>  '(UTC+02:00) Athens, Bucharest',
    'Europe/Istanbul'  =>  '(UTC+02:00) Istanbul',
    'Asia/Jerusalem'  =>  '(UTC+02:00) Jerusalem',
    'Asia/Amman'  =>  '(UTC+02:00) Amman',
    'Asia/Beirut'  =>  '(UTC+02:00) Beirut',
    'Africa/Windhoek'  =>  '(UTC+02:00) Windhoek',
    'Africa/Harare'  =>  '(UTC+02:00) Harare',
    'Asia/Kuwait'  =>  '(UTC+03:00) Kuwait, Riyadh',
    'Asia/Baghdad'  =>  '(UTC+03:00) Baghdad',
    'Africa/Nairobi'  =>  '(UTC+03:00) Nairobi',
    'Asia/Tehran'  =>  '(UTC+03:30) Tehran',
    'Asia/Tbilisi'  =>  '(UTC+04:00) Tbilisi',
    'Europe/Moscow'  =>  '(UTC+04:00) Moscow, Volgograd',
    'Asia/Muscat'  =>  '(UTC+04:00) Abu Dhabi, Muscat',
    'Asia/Baku'  =>  '(UTC+04:00) Baku',
    'Asia/Yerevan'  =>  '(UTC+04:00) Yerevan',
    'Asia/Karachi'  =>  '(UTC+05:00) Islamabad, Karachi',
    'Asia/Tashkent'  =>  '(UTC+05:00) Tashkent',
    'Asia/Kolkata'  =>  '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
    'Asia/Colombo'  =>  '(UTC+05:30) Sri Jayawardenepura',
    'Asia/Katmandu'  =>  '(UTC+05:45) Kathmandu',
    'Asia/Dhaka'  =>  '(UTC+06:00) Dhaka',
    'Asia/Almaty'  =>  '(UTC+06:00) Almaty',
    'Asia/Yekaterinburg'  =>  '(UTC+06:00) Ekaterinburg',
    'Asia/Rangoon'  =>  '(UTC+06:30) Yangon (Rangoon)',
    'Asia/Novosibirsk'  =>  '(UTC+07:00) Novosibirsk',
    'Asia/Bangkok'  =>  '(UTC+07:00) Bangkok, Jakarta',
    'Asia/Brunei'  =>  '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
    'Asia/Krasnoyarsk'  =>  '(UTC+08:00) Krasnoyarsk',
    'Asia/Ulaanbaatar'  =>  '(UTC+08:00) Ulaan Bataar',
    'Asia/Kuala_Lumpur'  =>  '(UTC+08:00) Kuala Lumpur, Singapore',
    'Asia/Taipei'  =>  '(UTC+08:00) Taipei',
    'Australia/Perth'  =>  '(UTC+08:00) Perth',
    'Asia/Irkutsk'  =>  '(UTC+09:00) Irkutsk',
    'Asia/Seoul'  =>  '(UTC+09:00) Seoul',
    'Asia/Tokyo'  =>  '(UTC+09:00) Tokyo',
    'Australia/Darwin'  =>  '(UTC+09:30) Darwin',
    'Australia/Adelaide'  =>  '(UTC+09:30) Adelaide',
    'Australia/Canberra'  =>  '(UTC+10:00) Canberra, Melbourne, Sydney',
    'Australia/Brisbane'  =>  '(UTC+10:00) Brisbane',
    'Australia/Hobart'  =>  '(UTC+10:00) Hobart',
    'Asia/Vladivostok'  =>  '(UTC+10:00) Vladivostok',
    'Pacific/Guam'  =>  '(UTC+10:00) Guam, Port Moresby',
    'Asia/Yakutsk'  =>  '(UTC+10:00) Yakutsk',
    'Pacific/Fiji'  =>  '(UTC+12:00) Fiji',
    'Asia/Kamchatka'  =>  '(UTC+12:00) Kamchatka',
    'Pacific/Auckland'  =>  '(UTC+12:00) Auckland',
    'Asia/Magadan'  =>  '(UTC+12:00) Magadan',
    'Pacific/Tongatapu'  =>  '(UTC+13:00) Nukualofa',
    
    // currency seperatar in user preferance
      'LBL_Space' => 'Space',
);

$jsLanguageStrings = array(
	//Curency seperator validation messages
	'JS_DECIMAL_SEPERATOR_AND_GROUPING_SEPERATOR_CANT_BE_SAME' => 'Десетичният разделител и груповият разделител трябва да бъдат различни',
	'JS_ENTER_CONFIRMATION_PASSWORD'=>'Моля, потвърдете вашата парола.',
	'JS_ENTER_NEW_PASSWORD'=>'Моля, въведете вашата нова парола.',
	'JS_ENTER_OLD_PASSWORD'=>'Моля, въведете вашата стара парола.',
	'JS_INVALID_PASSWORD'=>'Вие трябва да въведете потребителско име и парола.',
	'JS_PASSWORD_CHANGE_FAILED_1'=>'Грешка при промяна на парола за потребител ',
	'JS_PASSWORD_CHANGE_FAILED_2'=>' грешка.  Новата парола трябва да бъде дефинирана.',
	'JS_PASSWORD_INCORRECT_OLD'=>'невалидна стара парола. Моля, въведете старата парола отново.',
	'JS_REENTER_PASSWORDS'=>'Моля, въведете паролите отново.  \"Нова парола\" и \"Потвърди парола\" трябва да съвпадат.',
);
